baseURL       = "http://example.org/"
languageCode  = "en-us"
title         = "Software Development and Consulting Company | Webdevelop Pro"

# Site Menus
[menu]
  [[menu.main]]
    identifier = "how-it-works"
    name    = "How it works"
    url     = "/startup-dev-kit"
    weight  = 1
  [[menu.main]]
    identifier = "our-devkit"
    name    = "Our DevKit"
    url     = "/startup-dev-kit"
    parent = "how-it-works"
    weight  = 1
  [[menu.main]]
    identifier = "our-workflow"
    name    = "Our workflow"
    url     = "/how-we-work"
    parent = "how-it-works"
    weight  = 2
  [[menu.main]]
    identifier = "our-approach"
    name    = "Our approach"
    url     = "/our-approach"
    parent = "how-it-works"
    weight  = 3
  [[menu.main]]
    identifier = "services"
    name    = "Services"
    url     = "/services"
    weight  = 2
  [[menu.main]]
    identifier = "ai-ml-development"
    name    = "AI/ML Development"
    url     = "services/ai-ml-development"
    parent = "services"
    weight  = 1
  [[menu.main]]
    identifier = "mvp-development"
    name    = "MVP Development"
    url     = "services/build-mvp-webdevelop-pro-devkit"
    parent = "services"
    weight  = 2
  [[menu.main]]
    identifier = "cto-as-a-service"
    name    = "CTO As A Service"
    url     = "services/cto-as-a-service"
    parent = "services"
    weight  = 3
  [[menu.main]]
    identifier = "dedicated-team"
    name    = "Dedicated team"
    url     = "services/building-and-managing-development-team"
    parent = "services"
    weight  = 4
  [[menu.main]]
    identifier = "e-commerce"
    name    = "E-commerce"
    url     = "services/e-commerce-software"
    parent = "services"
    weight  = 5
  [[menu.main]]
    identifier = "iot-softwaree"
    name    = "IoT Software"
    url     = "services/iot-software"
    parent = "services"
    weight  = 6
  [[menu.main]]
    identifier = "fintech-software"
    name    = "Fintech Software"
    url     = "services/fintech-software"
    parent = "services"
    weight  = 7
  [[menu.main]]
    identifier = "resources"
    name    = "Resources"
    url     = "/blog"
    weight  = 3
  [[menu.main]]
    identifier = "company"
    name    = "Company"
    url     = "/company/about"
    weight  = 4
  [[menu.main]]
    identifier = "our-team"
    name    = "Our Team"
    url     = "/company/about"
    parent = "company"
    weight  = 1
  [[menu.main]]
    identifier = "contact-us"
    name    = "Contact Us"
    url     = "/company/contacts"
    parent = "company"
    weight  = 2
  [[menu.main]]
    identifier = "careers"
    name    = "Careers"
    url     = "/company/careers"
    parent = "company"
    weight  = 3
  

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Webdevelop Pro is the full-stack software development and consulting company that can drive a project from an early stage idea to a stable business."
  author = "Webdevelop Pro LLC"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"

  [params.header]
    top_notif_url = "company/help-ukraine"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Unparalleled software development"
    tagline               = "Full-stack software development and consulting for your world-changing business"
    primary_button        = "See Our Works"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "OUR RECENT WORKS"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "713 Elmwood St.<br>Prior Lake, MN 55372"
      phone   = "409-896-1444"
      email   = "info@roxo.co"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "#"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "We help brands:"
        description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"