baseURL       = "http://example.org/"
languageCode  = "en-us"
title         = "Software Development and Consulting Company | Webdevelop Pro"
# Disqus Comment System
disqusShortname = "webdevelop-pro"
[taxonomies]
  case = "cases"
  author = "authors"
  tag = "tags"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
# Site Menus
[menu]
  [[menu.main]]
    identifier = "how-it-works"
    name    = "How it works"
    url     = "/startup-dev-kit"
    weight  = 1
  [[menu.main]]
    identifier = "our-devkit"
    name    = "Our DevKit"
    url     = "/startup-dev-kit"
    parent = "how-it-works"
    weight  = 1
  [[menu.main]]
    identifier = "our-workflow"
    name    = "Our workflow"
    url     = "/how-we-work"
    parent = "how-it-works"
    weight  = 2
  [[menu.main]]
    identifier = "our-approach"
    name    = "Our approach"
    url     = "/our-approach"
    parent = "how-it-works"
    weight  = 3
  [[menu.main]]
    identifier = "services"
    name    = "Services"
    url     = "/services"
    weight  = 2
  [[menu.main]]
    identifier = "ai-ml-development"
    name    = "AI/ML Development"
    url     = "services/ai-ml-development"
    parent = "services"
    weight  = 1
  [[menu.main]]
    identifier = "mvp-development"
    name    = "MVP Development"
    url     = "services/build-mvp-webdevelop-pro-devkit"
    parent = "services"
    weight  = 2
  [[menu.main]]
    identifier = "cto-as-a-service"
    name    = "CTO As A Service"
    url     = "services/cto-as-a-service"
    parent = "services"
    weight  = 3
  [[menu.main]]
    identifier = "dedicated-team"
    name    = "Dedicated team"
    url     = "services/building-and-managing-development-team"
    parent = "services"
    weight  = 4
  [[menu.main]]
    identifier = "e-commerce"
    name    = "E-commerce"
    url     = "services/e-commerce-software"
    parent = "services"
    weight  = 5
  [[menu.main]]
    identifier = "iot-softwaree"
    name    = "IoT Software"
    url     = "services/iot-software"
    parent = "services"
    weight  = 6
  [[menu.main]]
    identifier = "fintech-software"
    name    = "Fintech Software"
    url     = "services/fintech-software"
    parent = "services"
    weight  = 7
  [[menu.main]]
    identifier = "resources"
    name    = "Resources"
    url     = "/blog"
    weight  = 3
  [[menu.main]]
    identifier = "company"
    name    = "Company"
    url     = "/about"
    weight  = 4
  [[menu.main]]
    identifier = "our-team"
    name    = "Our Team"
    url     = "/about"
    parent = "company"
    weight  = 1
  [[menu.main]]
    identifier = "contact-us"
    name    = "Contact Us"
    url     = "/contacts"
    parent = "company"
    weight  = 2
  [[menu.main]]
    identifier = "careers"
    name    = "Careers"
    url     = "/careers"
    parent = "company"
    weight  = 3
  

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Webdevelop Pro is the full-stack software development and consulting company that can drive a project from an early stage idea to a stable business."
  author = "Webdevelop Pro LLC"
  # Google Analitycs
  googleAnalitycsID = "Your ID"

  [params.header]
    top_notif_url = "/help-ukraine"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Unparalleled software development"
    tagline               = "Full-stack software development and consulting for your world-changing business"
    primary_button        = "See Our Works"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      [[params.footer.contactInfo.item]]
        title   = "USA"
        city    = "San Francisco"
        phone   = "+1 609 733 7724"
        email   = "manager@webdevelop.pro"
      [[params.footer.contactInfo.item]]
        title   = "Ukraine"
        city    = "Kyiv"
        phone   = "+38 063 440 5605"
        email   = "manager@webdevelop.pro"
      # Footer Social Media
      [params.footer.social]
        [[params.footer.social.link]]
          img = "images/facebook-icon.svg"
          url = "https://www.facebook.com/WebdevelopPro/"
        [[params.footer.social.link]]
          img = "images/instagram-icon.svg"
          url = "https://www.instagram.com/webdevelop.pro/"
        [[params.footer.social.link]]
          img = "images/linkedin-icon.svg"
          url = "https://www.linkedin.com/company/webdevelop-pro/"
        [[params.footer.social.link]]
          img = "images/github-icon.svg"
          url = "https://github.com/webdevelop-pro"
      # Footer Menu
      [params.footer.menu]
        [[params.footer.menu.item]]
          name = "About us"
          url  = "/about"
        [[params.footer.menu.item]]
          name = "How it works"
          url  = "/startup-dev-kit"
        [[params.footer.menu.item]]
          name = "Contacts"
          url  = "/contacts"
        [[params.footer.menu.item]]
          name = "Resources"
          url  = "/blog"